
GET http://localhost:5078/games
###
GET http://localhost:5078/games/57F0A570-A51F-4964-B4BD-3C02F4B3E90F
###
GET http://localhost:5078/genres
###
GET http://localhost:5078/ratings
###
DELETE http://localhost:5078/games/af45b776-3781-4880-b28a-20e5d65f6b1b
###
POST http://localhost:5078/games/
Content-Type: application/json

{
    "name": "Final Fantasy 7 Remake",
    "genreId": "2F77B8B2-2CA7-4DAB-A048-952955FBF10F",
    "ratingId": "4A386C1B-7F13-45FC-9843-B3EEDCF674D7",
    "releaseDate": "2020-04-10",
    "price": 40.99,
    "description": "Final Fantasy VII Remake is a modern reimagining of the 1997 PlayStation classic."
}

###
PUT http://localhost:5078/games/dafa23cb-b811-4764-8774-f34df6dbe892
Content-Type: application/json

{   "name": "Final Fantasy 7 Snake",
    "genreId": "935b4ae6-f3a3-442e-b984-32dc6ef7daf9",
    "ratingId": "a15fb383-11fa-4658-8e52-e591d545e46e",
    "releaseDate": "2023-04-10",
    "price": 33.33,
    "description": "Final Fantasy VII Remake is a modern reimagining of the 1997 PlayStation classic."
    }

